# Sortir Configuration

# Whether to sort elements across empty lines
# When false (default), sorting only happens within groups (elements not separated by empty lines)
ignoreGroups: false

# Filter elements with a specific prefix. Elements without this prefix will be excluded from sorting.
filterPrefix: ""

# Check constant declarations (const blocks)
constants:
 enabled: true
 prefix: ""

# Check variable declarations (var blocks)
variables:
 enabled: true
 prefix: ""

# Check struct field ordering
structFields:
 enabled: true
 prefix: ""

# Check interface method ordering
interfaceMethods:
 enabled: true
 prefix: ""

# Check variadic arguments in function calls
variadicArgs:
 enabled: false
 prefix: ""

# Check map literal value ordering by key
mapValues:
 enabled: true
 prefix: ""

# Whether to automatically fix sorting issues
fixMode: false

# Enable detailed logging
verbose: false
