# Sortir Configuration

# Whether to sort elements across empty lines
# When false (default), sorting only happens within groups (elements not separated by empty lines)
sort_across_empty_lines: false

# Specify which element types to check for sorting
enabled_checks:
  # Check constant declarations (const blocks)
  constants: true
  
  # Check variable declarations (var blocks)
  variables: true
  
  # Check struct field ordering
  struct_fields: true
  
  # Check interface method ordering
  interface_methods: true
  
  # Check variadic arguments in function calls
  variadic_args: true
  
  # Check map literal value ordering by key
  map_values: true

# Whether to automatically fix sorting issues
fix_mode: false

# Enable detailed logging
verbose: false